### ISSUE TITLE
Your Comments for DG Here! (CS2103 Tutorial Week 10)

### ISSUE THREAD

**Issue by nigelnnk** [AY1920S2-CS2103-W15-3/main#116]
Leave your comments for our DG here!

**Comment by zenatrick** [comment]
# Review by W17-3 
## Overall
- Many areas still have traces of AddressBook 3, you may want to remove them asap.
## Design
- Not much to comment
## Implementation
![image](https://user-images.githubusercontent.com/43820142/77569617-6b10bc80-6f05-11ea-9a1a-b91819dd7975.png)
- In 3.3.1, you may want to consider changing the following yellow highlight code block highlighted in the above picture:
    - from `consult` to `Consult`
    - from `XYZConsultCommands` to `XYZConsultCommand`s
    - from `XYZConsultCommandParsers` to `XYZConsultCommandParser`s
    - from `Consults` to `Consult`s
- In 3.3.1, you may want to consider changing the following green highlight words in the above picture to code blocks since they are taken from your actual code. (i.e. beginDateTime can be changed to `beginDateTime`)
- In 3.3.2, good use of the table to organise your pros and cons.
- In Figure 10, there is a small mistake. Your activation bar for `t:Tutorial` extends all the way to the bottom of the diagram.
- In Figure 10 and 12, you may want to state that the lifeline of `:NoteModCommandParser` continues after deletion due to the limitation of PlantUML (addressbook 3's DG have an example)
